### PR TITLE
Problem in making new video sticker

### PR DESCRIPTION
**Pull request by iamgojoof6eyes**
Unable to make new video sticker set.........getting the same problem as before when trying to make new normal sticker set

### CODE REVIEW

**Comment by HellBoy-OP** [comment]
if you'll add packname and packnick in the if statement (if not is_anim & not is_vid) then how'll the addition assignment work for is_anim and is_vid statements?

**Comment by iamgojoof6eyes** [comment]
If the first statement will be true then it will be executed....else the is_anim or is_vid statement will be executed

**Comment by iamgojoof6eyes** [comment]
because the bot is unable to make new vid sticker set one first set is filled completely

**Comment by HellBoy-OP** [comment]
and what if first is wrong? how will `packname +=` work in other 2 statements

**Comment by HellBoy-OP** [comment]
> because the bot is unable to make new vid sticker set one first set is filled completely

go to stickers bot pm and check where it's doing wronh

**Comment by iamgojoof6eyes** [comment]
will work normally maybe.......because if the statement is found to be wrong it will not execute anything just move to the next condition.........and I have checked it......it is just sending sticker name then sticker then emoji then /done......

**Comment by iamgojoof6eyes** [comment]
> 
will work normally maybe.......because if the statement is found to be wrong it will not execute anything just move to the next condition.........and I have checked it......it is just sending sticker name then sticker then emoji then /done......

**Comment by HellBoy-OP** [comment]
> will work normally maybe.......because if the statement is found to be wrong it will not execute anything just move to the next condition.........and I have checked it......it is just sending sticker name then sticker then emoji then /done......

i dont think

**Comment by iamgojoof6eyes** [comment]
> > will work normally maybe.......because if the statement is found to be wrong it will not execute anything just move to the next condition.........and I have checked it......it is just sending sticker name then sticker then emoji then /done......
> 
> i dont think

Maybe u know better than me......I think so that code should be like this so I just edited it

**Comment by HellBoy-OP** [comment]
> > > will work normally maybe.......because if the statement is found to be wrong it will not execute anything just move to the next condition.........and I have checked it......it is just sending sticker name then sticker then emoji then /done......
> > 
> > 
> > i dont think
> 
> Maybe u know better than me......I think so that code should be like this so I just edited it

once check where bot is doing mistake while creating new pack in stickers pm

**Comment by iamgojoof6eyes** [comment]
wait I'll ask my friend to send u screen shots

**Pull request closed without merging**
